Fixing the PHP 5.5 Compatibility
alexander-schranz/sulu-standard pull request #1
Opened 2018-06-25 13:55 UTC by ilyabakhlin

Hello, @alexander-schranz!

I've noticed you're trying to solve the compatibility for the PHP 5.5, so I got curious and decided to contribute finding the solution.

What I found is the following:

1. The project's dependencies are already suitable with the mentioned version of the PHP language.
2. The problem resides in the absence of the `composer.lock` file and in the preparation of the project for the tests with `beforetests.sh` file.

After checking the history of the `beforetests.sh` file, I saw to @danrot remove the `composer.lock` file and install the dependencies of the project with the `composer update` command, substituting with it the previous `composer install` one, as you can check in [this commit](https://github.com/sulu/sulu-standard/commit/23937c13bbf980d1502cf87895a7dee132c0dd7d#diff-1d106eec3eae32c7d6813dd38807ae21).

Handling the dependencies in that way is a risky practice, as it's described in [this article](https://adamcod.es/2013/03/07/composer-install-vs-composer-update.html), which I recommend you to have a look.

I hope this pull request will help you to continue with the project.

Regards.

2018-06-25 14:00 UTC, ilyabakhlin commented
Here are the builds with passing tests on my Travis CI account: https://travis-ci.org/ilyabakhlin/sulu-standard

2018-06-25 14:22 UTC, alexander-schranz commented
Hello @ilyabakhlin, 

there is no difference between `composer install` and `composer update` if no composer.lock exists. And in case of sulu-standard it would not be possible to provide a `composer.lock` file. As the lock file is specific for the PHP Version which did run the composer command so a library/skeleton/boilerplate which supports multiple PHP Version will never and should never provide a composer.lock file.

That the composer.lock is removed from your .gitignore we created a composer hook when you create your new project https://github.com/sulu/sulu-standard/blob/f2ee0b9c0e0be866562be0284ef191a049e986d5/composer.json#L78.

The problem is not PHP5.5 its PHP5.5 on --prefer-lowest which is ignored by your PR as you run without `$COMPOSER_FLAGS`. So the only things which need to change are some minimum requirements. As you can see in: https://github.com/sulu/sulu-standard/pull/845/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

2018-06-25 14:40 UTC, ilyabakhlin commented
As I can see in the [`composer install`](https://getcomposer.org/doc/03-cli.md#install) command documentation, there is no acceptable argument `--prefer-lowest` because the mentioned command install the exact version specified in the `composer.json` file, giving me to understand that there are only two arguments missing, which are the following: `--prefer-dist` and `--no-interaction` I can add right now.

On the other hand, I do use the `$COMPOSER_FLAGS` variable with the `composer update` command, and you can see how this last one updates installed packages, without compromising the build of the project during the Travis CI execution.

2018-06-26 07:41 UTC, ilyabakhlin commented
Are you interested in this pull request? If you aren't, just close it. Otherwise, I'd really like you to merge it.

2018-06-27 12:23 UTC, alexander-schranz commented
@ilyabakhlin the composer install is only a workaround for a composer bug with prefer-lowest. Can you add a `if` statement that we run this only in when `composerflags` contains `prefer-lowest` and add a comment that this can be removed when https://github.com/composer/composer/issues/7161 is fixed.

2018-06-28 07:56 UTC, ilyabakhlin commented
Done. I haven't understood what do you mean by leaving a comment, but as this pull request goes to your branch, which is up to be merged to the official project, I guess you can add the comment you find appropriate.

2018-06-28 08:21 UTC, alexander-schranz requested changes

2018-06-28 08:21 UTC, alexander-schranz commented on tests/beforetests.sh
> +    composer update $COMPOSER_FLAGS
else can be avoided and add a comment why e.g.:

```bash
# FIXME hack for prefer-lowest bug: https://github.com/composer/composer/issues/7161
if [[ $COMPOSER_FLAGS == *"--prefer-lowest"* ]]; then
    composer install && composer update $COMPOSER_FLAGS
fi
composer update $COMPOSER_FLAGS
```

2018-06-28 09:03 UTC, ilyabakhlin commented
Done.

2018-06-28 09:06 UTC, merged

2018-06-28 09:06 UTC, alexander-schranz commented
@ilyabakhlin awesome thank you!